/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mia.Coupon;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-08-18")
public class TParamsCheckoutCommonCoupon implements org.apache.thrift.TBase<TParamsCheckoutCommonCoupon, TParamsCheckoutCommonCoupon._Fields>, java.io.Serializable, Cloneable, Comparable<TParamsCheckoutCommonCoupon> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TParamsCheckoutCommonCoupon");

  private static final org.apache.thrift.protocol.TField T_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("tContent", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField T_CHECKOUT_COUPON_FIELD_DESC = new org.apache.thrift.protocol.TField("tCheckoutCoupon", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TParamsCheckoutCommonCouponStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TParamsCheckoutCommonCouponTupleSchemeFactory());
  }

  public TContent tContent; // required
  public TCheckoutCoupon tCheckoutCoupon; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    T_CONTENT((short)1, "tContent"),
    T_CHECKOUT_COUPON((short)2, "tCheckoutCoupon");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // T_CONTENT
          return T_CONTENT;
        case 2: // T_CHECKOUT_COUPON
          return T_CHECKOUT_COUPON;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.T_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("tContent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "TContent")));
    tmpMap.put(_Fields.T_CHECKOUT_COUPON, new org.apache.thrift.meta_data.FieldMetaData("tCheckoutCoupon", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "TCheckoutCoupon")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TParamsCheckoutCommonCoupon.class, metaDataMap);
  }

  public TParamsCheckoutCommonCoupon() {
  }

  public TParamsCheckoutCommonCoupon(
    TContent tContent,
    TCheckoutCoupon tCheckoutCoupon)
  {
    this();
    this.tContent = tContent;
    this.tCheckoutCoupon = tCheckoutCoupon;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TParamsCheckoutCommonCoupon(TParamsCheckoutCommonCoupon other) {
    if (other.isSetTContent()) {
      this.tContent = other.tContent;
    }
    if (other.isSetTCheckoutCoupon()) {
      this.tCheckoutCoupon = other.tCheckoutCoupon;
    }
  }

  public TParamsCheckoutCommonCoupon deepCopy() {
    return new TParamsCheckoutCommonCoupon(this);
  }

  @Override
  public void clear() {
    this.tContent = null;
    this.tCheckoutCoupon = null;
  }

  public TContent getTContent() {
    return this.tContent;
  }

  public TParamsCheckoutCommonCoupon setTContent(TContent tContent) {
    this.tContent = tContent;
    return this;
  }

  public void unsetTContent() {
    this.tContent = null;
  }

  /** Returns true if field tContent is set (has been assigned a value) and false otherwise */
  public boolean isSetTContent() {
    return this.tContent != null;
  }

  public void setTContentIsSet(boolean value) {
    if (!value) {
      this.tContent = null;
    }
  }

  public TCheckoutCoupon getTCheckoutCoupon() {
    return this.tCheckoutCoupon;
  }

  public TParamsCheckoutCommonCoupon setTCheckoutCoupon(TCheckoutCoupon tCheckoutCoupon) {
    this.tCheckoutCoupon = tCheckoutCoupon;
    return this;
  }

  public void unsetTCheckoutCoupon() {
    this.tCheckoutCoupon = null;
  }

  /** Returns true if field tCheckoutCoupon is set (has been assigned a value) and false otherwise */
  public boolean isSetTCheckoutCoupon() {
    return this.tCheckoutCoupon != null;
  }

  public void setTCheckoutCouponIsSet(boolean value) {
    if (!value) {
      this.tCheckoutCoupon = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case T_CONTENT:
      if (value == null) {
        unsetTContent();
      } else {
        setTContent((TContent)value);
      }
      break;

    case T_CHECKOUT_COUPON:
      if (value == null) {
        unsetTCheckoutCoupon();
      } else {
        setTCheckoutCoupon((TCheckoutCoupon)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case T_CONTENT:
      return getTContent();

    case T_CHECKOUT_COUPON:
      return getTCheckoutCoupon();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case T_CONTENT:
      return isSetTContent();
    case T_CHECKOUT_COUPON:
      return isSetTCheckoutCoupon();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TParamsCheckoutCommonCoupon)
      return this.equals((TParamsCheckoutCommonCoupon)that);
    return false;
  }

  public boolean equals(TParamsCheckoutCommonCoupon that) {
    if (that == null)
      return false;

    boolean this_present_tContent = true && this.isSetTContent();
    boolean that_present_tContent = true && that.isSetTContent();
    if (this_present_tContent || that_present_tContent) {
      if (!(this_present_tContent && that_present_tContent))
        return false;
      if (!this.tContent.equals(that.tContent))
        return false;
    }

    boolean this_present_tCheckoutCoupon = true && this.isSetTCheckoutCoupon();
    boolean that_present_tCheckoutCoupon = true && that.isSetTCheckoutCoupon();
    if (this_present_tCheckoutCoupon || that_present_tCheckoutCoupon) {
      if (!(this_present_tCheckoutCoupon && that_present_tCheckoutCoupon))
        return false;
      if (!this.tCheckoutCoupon.equals(that.tCheckoutCoupon))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_tContent = true && (isSetTContent());
    list.add(present_tContent);
    if (present_tContent)
      list.add(tContent);

    boolean present_tCheckoutCoupon = true && (isSetTCheckoutCoupon());
    list.add(present_tCheckoutCoupon);
    if (present_tCheckoutCoupon)
      list.add(tCheckoutCoupon);

    return list.hashCode();
  }

  @Override
  public int compareTo(TParamsCheckoutCommonCoupon other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTContent()).compareTo(other.isSetTContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tContent, other.tContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTCheckoutCoupon()).compareTo(other.isSetTCheckoutCoupon());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTCheckoutCoupon()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tCheckoutCoupon, other.tCheckoutCoupon);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TParamsCheckoutCommonCoupon(");
    boolean first = true;

    sb.append("tContent:");
    if (this.tContent == null) {
      sb.append("null");
    } else {
      sb.append(this.tContent);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tCheckoutCoupon:");
    if (this.tCheckoutCoupon == null) {
      sb.append("null");
    } else {
      sb.append(this.tCheckoutCoupon);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TParamsCheckoutCommonCouponStandardSchemeFactory implements SchemeFactory {
    public TParamsCheckoutCommonCouponStandardScheme getScheme() {
      return new TParamsCheckoutCommonCouponStandardScheme();
    }
  }

  private static class TParamsCheckoutCommonCouponStandardScheme extends StandardScheme<TParamsCheckoutCommonCoupon> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TParamsCheckoutCommonCoupon struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // T_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.tContent = new TContent();
              struct.tContent.read(iprot);
              struct.setTContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // T_CHECKOUT_COUPON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.tCheckoutCoupon = new TCheckoutCoupon();
              struct.tCheckoutCoupon.read(iprot);
              struct.setTCheckoutCouponIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TParamsCheckoutCommonCoupon struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tContent != null) {
        oprot.writeFieldBegin(T_CONTENT_FIELD_DESC);
        struct.tContent.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.tCheckoutCoupon != null) {
        oprot.writeFieldBegin(T_CHECKOUT_COUPON_FIELD_DESC);
        struct.tCheckoutCoupon.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TParamsCheckoutCommonCouponTupleSchemeFactory implements SchemeFactory {
    public TParamsCheckoutCommonCouponTupleScheme getScheme() {
      return new TParamsCheckoutCommonCouponTupleScheme();
    }
  }

  private static class TParamsCheckoutCommonCouponTupleScheme extends TupleScheme<TParamsCheckoutCommonCoupon> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TParamsCheckoutCommonCoupon struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTContent()) {
        optionals.set(0);
      }
      if (struct.isSetTCheckoutCoupon()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTContent()) {
        struct.tContent.write(oprot);
      }
      if (struct.isSetTCheckoutCoupon()) {
        struct.tCheckoutCoupon.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TParamsCheckoutCommonCoupon struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.tContent = new TContent();
        struct.tContent.read(iprot);
        struct.setTContentIsSet(true);
      }
      if (incoming.get(1)) {
        struct.tCheckoutCoupon = new TCheckoutCoupon();
        struct.tCheckoutCoupon.read(iprot);
        struct.setTCheckoutCouponIsSet(true);
      }
    }
  }

}

