/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mia.Coupon;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-08-18")
public class TParamsRecoverCoupon implements org.apache.thrift.TBase<TParamsRecoverCoupon, TParamsRecoverCoupon._Fields>, java.io.Serializable, Cloneable, Comparable<TParamsRecoverCoupon> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TParamsRecoverCoupon");

  private static final org.apache.thrift.protocol.TField SUPERIOR_ORDER_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("superiorOrderCode", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TParamsRecoverCouponStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TParamsRecoverCouponTupleSchemeFactory());
  }

  public String superiorOrderCode; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SUPERIOR_ORDER_CODE((short)1, "superiorOrderCode");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SUPERIOR_ORDER_CODE
          return SUPERIOR_ORDER_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SUPERIOR_ORDER_CODE, new org.apache.thrift.meta_data.FieldMetaData("superiorOrderCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TParamsRecoverCoupon.class, metaDataMap);
  }

  public TParamsRecoverCoupon() {
  }

  public TParamsRecoverCoupon(
    String superiorOrderCode)
  {
    this();
    this.superiorOrderCode = superiorOrderCode;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TParamsRecoverCoupon(TParamsRecoverCoupon other) {
    if (other.isSetSuperiorOrderCode()) {
      this.superiorOrderCode = other.superiorOrderCode;
    }
  }

  public TParamsRecoverCoupon deepCopy() {
    return new TParamsRecoverCoupon(this);
  }

  @Override
  public void clear() {
    this.superiorOrderCode = null;
  }

  public String getSuperiorOrderCode() {
    return this.superiorOrderCode;
  }

  public TParamsRecoverCoupon setSuperiorOrderCode(String superiorOrderCode) {
    this.superiorOrderCode = superiorOrderCode;
    return this;
  }

  public void unsetSuperiorOrderCode() {
    this.superiorOrderCode = null;
  }

  /** Returns true if field superiorOrderCode is set (has been assigned a value) and false otherwise */
  public boolean isSetSuperiorOrderCode() {
    return this.superiorOrderCode != null;
  }

  public void setSuperiorOrderCodeIsSet(boolean value) {
    if (!value) {
      this.superiorOrderCode = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SUPERIOR_ORDER_CODE:
      if (value == null) {
        unsetSuperiorOrderCode();
      } else {
        setSuperiorOrderCode((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SUPERIOR_ORDER_CODE:
      return getSuperiorOrderCode();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SUPERIOR_ORDER_CODE:
      return isSetSuperiorOrderCode();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TParamsRecoverCoupon)
      return this.equals((TParamsRecoverCoupon)that);
    return false;
  }

  public boolean equals(TParamsRecoverCoupon that) {
    if (that == null)
      return false;

    boolean this_present_superiorOrderCode = true && this.isSetSuperiorOrderCode();
    boolean that_present_superiorOrderCode = true && that.isSetSuperiorOrderCode();
    if (this_present_superiorOrderCode || that_present_superiorOrderCode) {
      if (!(this_present_superiorOrderCode && that_present_superiorOrderCode))
        return false;
      if (!this.superiorOrderCode.equals(that.superiorOrderCode))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_superiorOrderCode = true && (isSetSuperiorOrderCode());
    list.add(present_superiorOrderCode);
    if (present_superiorOrderCode)
      list.add(superiorOrderCode);

    return list.hashCode();
  }

  @Override
  public int compareTo(TParamsRecoverCoupon other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSuperiorOrderCode()).compareTo(other.isSetSuperiorOrderCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuperiorOrderCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.superiorOrderCode, other.superiorOrderCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TParamsRecoverCoupon(");
    boolean first = true;

    sb.append("superiorOrderCode:");
    if (this.superiorOrderCode == null) {
      sb.append("null");
    } else {
      sb.append(this.superiorOrderCode);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TParamsRecoverCouponStandardSchemeFactory implements SchemeFactory {
    public TParamsRecoverCouponStandardScheme getScheme() {
      return new TParamsRecoverCouponStandardScheme();
    }
  }

  private static class TParamsRecoverCouponStandardScheme extends StandardScheme<TParamsRecoverCoupon> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TParamsRecoverCoupon struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SUPERIOR_ORDER_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.superiorOrderCode = iprot.readString();
              struct.setSuperiorOrderCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TParamsRecoverCoupon struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.superiorOrderCode != null) {
        oprot.writeFieldBegin(SUPERIOR_ORDER_CODE_FIELD_DESC);
        oprot.writeString(struct.superiorOrderCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TParamsRecoverCouponTupleSchemeFactory implements SchemeFactory {
    public TParamsRecoverCouponTupleScheme getScheme() {
      return new TParamsRecoverCouponTupleScheme();
    }
  }

  private static class TParamsRecoverCouponTupleScheme extends TupleScheme<TParamsRecoverCoupon> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TParamsRecoverCoupon struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSuperiorOrderCode()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetSuperiorOrderCode()) {
        oprot.writeString(struct.superiorOrderCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TParamsRecoverCoupon struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.superiorOrderCode = iprot.readString();
        struct.setSuperiorOrderCodeIsSet(true);
      }
    }
  }

}

