/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mia.Coupon;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TUserCouponStatus implements org.apache.thrift.TEnum {
  NoUse(1),
  Used(2),
  Expired(3);

  private final int value;

  private TUserCouponStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TUserCouponStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return NoUse;
      case 2:
        return Used;
      case 3:
        return Expired;
      default:
        return null;
    }
  }
}
